import { Typography } from "@mui/material";
import { useEffect, useState } from "react";

import style from "./style.module.css";

export const Curiosidades = () => {
  const curiosidades = [
    "A abelha rainha pode viver até 5 anos, enquanto as operárias vivem apenas algumas semanas.",
    "O Monte Everest não é a montanha mais alta do mundo, se medido a partir do fundo do oceano, o título vai para o Mauna Kea no Havaí.",
    "O cheiro da chuva tem um nome: petricor.",
    "As vacas têm melhores amigas e podem ficar estressadas quando são separadas delas.",
    "Um raio pode aquecer o ar ao seu redor a uma temperatura cinco vezes mais quente que a superfície do sol.",
    "O olho humano é capaz de distinguir mais de 10 milhões de cores.",
    "O som não se propaga no vácuo, o que significa que no espaço sideral, ninguém pode ouvir você gritar.",
    "A Biblioteca de Alexandria, no Egito, continha uma vasta quantidade de conhecimento antigo e foi destruída por diversos eventos ao longo dos séculos.",
    "A quantidade de árvores na Terra é estimada em cerca de 3 trilhões.",
    "O material mais resistente do mundo é o grafeno, composto por uma única camada de átomos de carbono.",
    "O primeiro computador eletrônico, o ENIAC, ocupava uma sala inteira e pesava cerca de 27 toneladas.",
    "O código-fonte do software Apollo 11, que levou o homem à lua, foi disponibilizado publicamente pela NASA.",
    "A capacidade de processamento do supercomputador mais rápido do mundo, o Fugaku, é de mais de 442 petaflops.",
    "O termo 'bug de computador' foi cunhado quando uma mariposa ficou presa em um relé no computador Mark II, em 1947.",
    "A Microsoft foi originalmente chamada de Micro-Soft e foi fundada por Bill Gates e Paul Allen em 1975.",
    "O primeiro smartphone com tela sensível ao toque foi o IBM Simon, lançado em 1992.",
    "A quantidade de transistores em um processador duplica a cada 18 meses, de acordo com a Lei de Moore.",
    "O mouse foi inventado por Douglas Engelbart em 1964 e foi feito de madeira.",
    "A Internet tem cerca de 4,2 bilhões de usuários, representando mais da metade da população mundial.",
    "O primeiro e-mail foi enviado por Ray Tomlinson em 1971. Ele escolheu a arroba (@) para separar o nome do usuário do nome da máquina.",
    "A Apple foi fundada em uma garagem por Steve Jobs, Steve Wozniak e Ronald Wayne.",
    "O sistema operacional Linux foi criado por Linus Torvalds em 1991 e é uma alternativa de código aberto ao Unix.",
    "O protocolo de comunicação padrão da Internet, o TCP/IP, foi desenvolvido por Vinton Cerf e Robert Kahn.",
    "O primeiro emoticon, :-) , foi usado por Scott Fahlman em 1982.",
    "A expressão 'surfando na web' foi cunhada por Jean Armour Polly em 1992.",
    "A palavra 'robot' foi introduzida por Karel Capek em sua peça de teatro 'R.U.R.' em 1920.",
    "A primeira mensagem de texto foi enviada em 1992 por Neil Papworth, que desejou 'Feliz Natal' a um amigo.",
    "A IBM lançou o primeiro disco rígido comercial em 1956, que tinha uma capacidade de armazenamento de 5 megabytes e pesava mais de uma tonelada.",
    "O QR Code foi inventado por Masahiro Hara em 1994.",
    "O primeiro smartphone Android, o HTC Dream, foi lançado em 2008.",
    "A sigla Wi-Fi não significa 'Wireless Fidelity', é uma marca registrada sem significado específico.",
    "O termo 'Bluetooth' é uma homenagem ao rei dinamarquês do século X, Harald 'Bluetooth' Gormsson.",
    "O primeiro computador pessoal, o Altair 8800, foi lançado em 1975.",
    "A linguagem de programação Python recebeu esse nome em homenagem ao grupo de comédia britânico Monty Python.",
    "A World Wide Web foi proposta por Tim Berners-Lee em 1989.",
    "O primeiro navegador web gráfico foi o Mosaic, lançado em 1993.",
    "A primeira webcam foi criada no laboratório de computação da Universidade de Cambridge para monitorar a cafeteira, permitindo que os usuários verificassem se ainda havia café.",
    "A linguagem de programação Java foi originalmente chamada de Oak.",
    "O primeiro videogame comercialmente bem-sucedido foi o Pong, lançado em 1972.",
    "O primeiro iPhone foi lançado em 2007 por Steve Jobs.",
    "Os elefantes são os únicos mamíferos que não conseguem pular.",
    "A baleia-azul é o maior animal do planeta, chegando a pesar até 200 toneladas.",
    "As formigas dormem apenas cerca de 4 minutos por dia.",
    "O beija-flor é a única ave capaz de voar para trás.",
    "A girafa tem a mesma quantidade de vértebras no pescoço que um ser humano, sete.",
    "Os pinguins têm uma única parceira de vida e costumam trocar 'presentes' para fortalecer o vínculo.",
    "O gato doméstico é descendente do gato selvagem africano e foi domesticado há mais de 4.000 anos.",
    "O nariz de um cachorro é único, assim como a impressão digital humana.",
    "O cérebro de um polvo é tão grande que a maior parte dele está em seus tentáculos.",
    "As abelhas podem reconhecer rostos humanos.",
    "Os cavalos têm uma memória excelente e conseguem lembrar-se de pessoas por anos.",
    "A língua de uma baleia-azul é tão grande que poderia acomodar cerca de 50 pessoas em pé sobre ela.",
    "O tigre tem listras não apenas na pele, mas também em seus ossos.",
    "Os cães têm cerca de 220 milhões de células olfativas, enquanto os humanos têm apenas 5 milhões.",
    "Os camaleões podem mover seus olhos de forma independente, permitindo-lhes olhar em duas direções ao mesmo tempo.",
    "As abelhas rainhas podem viver até cinco anos, enquanto as operárias vivem apenas algumas semanas.",
    "O nariz de um cachorro é tão único quanto a impressão digital de um humano.",
    "Os morcegos são os únicos mamíferos capazes de voar.",
    "As lagartixas conseguem regenerar suas caudas.",
    "Os polvos têm três corações e o sangue azul.",
    "Os crocodilos não conseguem movimentar suas línguas, pois são conectadas ao céu da boca.",
    "O elefante africano é o maior herbívoro terrestre.",
    "O bico do tucano é forte, mas surpreendentemente leve, composto principalmente de queratina.",
    "O leão-marinho é um mamífero que pode dormir em águas profundas enquanto permanece acordado para respirar.",
    "A fêmea do mosquito é a responsável pelas picadas, pois precisa do sangue para alimentar seus ovos.",
    "As cabras têm pupilas retangulares, proporcionando uma visão de 320 a 340 graus.",
    "Os polvos têm a capacidade de se camuflar, imitando a aparência e textura de seu ambiente.",
    "Os corvos são conhecidos por usar ferramentas e até mesmo por criar suas próprias ferramentas para obter comida.",
    "As abelhas dançam para se comunicar com as outras sobre a localização de fontes de alimento.",
    "O narval, conhecido como o 'unicórnio do mar', tem um longo dente retorcido que pode atingir até 3 metros de comprimento.",
    "O Sol representa mais de 99% da massa do sistema solar.",
    "A Via Láctea, nossa galáxia, contém mais de 100 bilhões de estrelas.",
    "A lua de Júpiter, Ganimedes, é a maior lua do sistema solar.",
    "Um ano em Vênus é mais curto que um dia no planeta devido à sua órbita mais rápida.",
    "A estrela mais próxima da Terra, Proxima Centauri, faz parte do sistema Alpha Centauri.",
    "A Grande Mancha Vermelha em Júpiter é uma tempestade gigante que dura pelo menos 350 anos.",
    "A gravidade em Netuno é 17 vezes mais forte que a da Terra.",
    "A teoria do Big Bang sugere que o universo começou como uma singularidade extremamente quente e densa.",
    "Os buracos negros são regiões do espaço-tempo onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar.",
    "Um pulsar é uma estrela de nêutrons que emite pulsos regulares de radiação eletromagnética.",
    "A Lua se afasta da Terra a uma taxa de cerca de 3,8 centímetros por ano.",
    "O Telescópio Espacial Hubble pode ver objetos tão distantes que sua luz viajou por bilhões de anos até alcançá-lo.",
    "A Nebulosa do Caranguejo é o resultado da explosão de uma supernova observada em 1054.",
    "A Voyager 1, lançada em 1977, é a sonda espacial mais distante da Terra.",
    "Um aglomerado de estrelas chamado Westerlund 1 contém algumas das estrelas mais massivas conhecidas.",
    "Existem mais de 200 bilhões de galáxias no universo observável.",
    "Os astronautas na Estação Espacial Internacional (EEI) experimentam cerca de 16 órbitas ao redor da Terra por dia.",
    "O som não pode se propagar no vácuo do espaço, tornando-o completamente silencioso.",
    "Os buracos de minhoca são hipotéticas passagens pelo espaço-tempo que poderiam permitir viagens interestelares.",
    "Cada estrela no céu pode pertencer a uma constelação, mas muitas estão mais próximas ou mais distantes do que parecem.",
    "A temperatura na atmosfera superior do Sol pode chegar a milhões de graus Celsius.",
    "Os cometas têm duas caudas: uma de poeira e uma de gás ionizado que sempre se afasta do Sol.",
    "A Lua não tem atmosfera, o que significa que não tem vento ou clima.",
    "A sonda espacial Juno está estudando o planeta Júpiter para entender melhor sua formação e evolução.",
    "Os quasares são núcleos galácticos ativos que emitem enormes quantidades de energia.",
    "O som não se propaga no espaço, mas os cientistas podem converter ondas eletromagnéticas em sons que podemos ouvir.",
    "A Teoria da Relatividade Geral de Einstein prevê a existência de buracos de minhoca, mas ainda não foram observados.",
    "A nebulosa de Órion é uma das regiões de formação estelar mais estudadas e fotografadas.",
    "A sonda Cassini estudou Saturno e suas luas por 13 anos antes de ser desativada em 2017.",
    "As bananas são tecnicamente bagas, enquanto morangos não são considerados verdadeiras bagas.",
    "O bambu é a planta que cresce mais rápido no mundo, podendo crescer até 91 centímetros em um dia.",
    "A flor da vanilla, que é usada para fazer baunilha, só pode ser polinizada por uma espécie específica de abelha encontrada no México.",
    "O algodão é uma fibra natural que cresce em torno das sementes do algodoeiro.",
    "A batata doce pertence à família das convolvuláceas, enquanto a batata comum pertence à família das solanáceas.",
    "O maior organismo vivo na Terra é um fungo chamado Armillaria ostoyae, que se estende por mais de 8,8 km² na floresta Malheur National, nos Estados Unidos.",
    "O girassol não é uma única flor, mas sim um conjunto de flores minúsculas organizadas em uma estrutura central.",
    "A planta de café pertence à família do jasmim.",
    "A raiz da mandioca é uma importante fonte de amido na alimentação em muitas partes do mundo.",
    "O abacaxi é uma fruta composta, formada por uma série de pequenos frutos individuais fundidos.",
    "A planta de cacau, de onde vem o chocolate, precisa ser cultivada em climas tropicais, geralmente a 20 graus norte e sul do equador.",
    "O aroma característico da menta é devido ao composto químico mentol encontrado nas folhas.",
    "O arroz é o alimento básico para mais da metade da população mundial.",
    "A maior árvore do mundo em volume é a sequoia gigante chamada General Sherman, localizada na Califórnia.",
    "O açafrão, usado como tempero, é derivado dos estigmas da flor Crocus sativus.",
    "As raízes da planta de wasabi são usadas para fazer o famoso condimento japonês, não as folhas.",
    "A flor de lótus pode crescer em ambientes aquáticos e suas sementes podem permanecer viáveis por centenas de anos.",
    "A papoula é cultivada para a produção de sementes de papoula, que são usadas na culinária e na fabricação de ópio.",
    "A batata foi a primeira planta cultivada no espaço, a bordo da estação espacial internacional em 1995.",
    "O agave, de onde vem o tequila, leva cerca de 8 anos para atingir a maturidade suficiente para a colheita.",
    "A canela é extraída da casca interna da árvore Cinnamomum.",
    "O girassol segue o movimento do sol durante o dia, um comportamento chamado heliotropismo.",
    "A orquídea baunilha é a única orquídea cultivada comercialmente por suas vagens de semente.",
    "A planta de tomate é nativa das Américas e não foi introduzida na Europa até o século XVI.",
    "O bambu é mais resistente que o aço, tornando-se um material de construção surpreendentemente durável.",
    "A quinoa é uma semente, não um grão, e é uma excelente fonte de proteína completa.",
    "O mel é produzido pelas abelhas a partir do néctar das flores, que é armazenado nas células da colmeia e evaporado para formar o mel.",
    "A planta de algodão foi domesticada há mais de 7.000 anos e é uma das mais antigas plantas cultivadas pelo homem.",
    "Aloe vera é conhecida por suas propriedades medicinais e é usada tradicionalmente para tratar queimaduras e feridas.",
    "O inhame e a batata doce são plantas diferentes, pertencendo a famílias botânicas distintas.",
    "O Brasil é o quinto maior país do mundo em área territorial.",
    "A Floresta Amazônica, localizada no Brasil, é a maior floresta tropical do mundo.",
    "O Carnaval do Rio de Janeiro é considerado o maior do mundo.",
    "O futebol é o esporte mais popular no Brasil, e o país já venceu a Copa do Mundo cinco vezes.",
    "A Amazônia brasileira abriga a maior diversidade de espécies de plantas e animais do planeta.",
    "O Cristo Redentor, no Rio de Janeiro, é uma das Sete Maravilhas do Mundo Moderno.",
    "O Pão de Açúcar, também no Rio de Janeiro, é um famoso ponto turístico brasileiro.",
    "O Brasil foi a última nação ocidental a abolir a escravidão, em 1888.",
    "A língua oficial do Brasil é o português, sendo o único país da América do Sul com essa língua predominante.",
    "A cidade de Manaus, localizada no coração da Amazônia, é uma das poucas cidades do mundo que possui uma floresta tropical dentro de seus limites urbanos.",
    "O Brasil é o maior produtor mundial de café.",
    "A Praia do Cassino, no Rio Grande do Sul, é a praia mais longa do mundo, com cerca de 254 km de extensão.",
    "A festa de São João, comemorada em junho, é uma das maiores festas populares do país.",
    "A Ilha de Marajó, no Pará, é a maior ilha fluviomarinha do mundo.",
    "O Parque Nacional do Iguaçu, que abriga as Cataratas do Iguaçu, é considerado Patrimônio Mundial Natural pela UNESCO.",
    "O Brasil é o maior produtor mundial de açúcar.",
    "O Museu Nacional, no Rio de Janeiro, já abrigou o maior acervo de história natural da América Latina antes de ser parcialmente destruído por um incêndio em 2018.",
    "A cidade de São Paulo é a maior metrópole do hemisfério sul.",
    "A Semana de Arte Moderna de 1922, em São Paulo, foi um marco cultural que influenciou a arte brasileira.",
    "O Círio de Nazaré, em Belém, é uma das maiores procissões religiosas do mundo.",
    "O Brasil é o maior exportador mundial de carne bovina.",
    "A cidade de Brasília foi planejada e construída para ser a capital do Brasil, substituindo o Rio de Janeiro.",
    "O futebol de areia, também conhecido como beach soccer, foi inventado no Brasil na década de 1990.",
    "O Rio Negro, no Amazonas, é o segundo maior rio do mundo em volume de água, depois do Rio Amazonas.",
    "O Mercado Modelo, em Salvador, é um famoso mercado de artesanato e produtos típicos da Bahia.",
    "A cidade de Ouro Preto, em Minas Gerais, é conhecida por sua arquitetura colonial e suas igrejas barrocas.",
    "A Bossa Nova, um estilo musical brasileiro, surgiu no final da década de 1950 no Rio de Janeiro.",
    "O Brasil é o maior produtor mundial de suco de laranja.",
    'A cidade de Recife é conhecida como a "Veneza brasileira" devido aos seus muitos rios, pontes e canais.',
    "A diversidade étnica e cultural do Brasil é refletida na culinária, que varia de região para região, incluindo pratos como feijoada, acarajé e churrasco.",
    "JavaScript foi originalmente criado em 10 dias por Brendan Eich em 1995.",
    "O nome 'JavaScript' foi escolhido por marketing para capitalizar o sucesso da linguagem Java.",
    "O ECMAScript é a especificação padrão que JavaScript implementa.",
    "O operador 'typeof' em JavaScript pode retornar 'object' para arrays, uma peculiaridade da linguagem.",
    "A palavra-chave 'this' em JavaScript pode se comportar de maneira diferente dependendo do contexto de execução.",
    "O conceito de closure, que permite que funções tenham acesso a variáveis de escopos externos, é uma característica fundamental em JavaScript.",
    "O padrão de design 'Module Pattern' em JavaScript utiliza closures para encapsular funcionalidades.",
    "O método 'forEach()' foi introduzido no ECMAScript 5 e facilita a iteração sobre elementos de arrays.",
    "O 'hoisting' é um comportamento em JavaScript em que declarações de variáveis e funções são movidas para o topo de seus escopos durante a fase de compilação.",
    "A função 'setTimeout()' em JavaScript é usada para atrasar a execução de uma função em um determinado tempo.",
    "JavaScript é uma linguagem orientada a eventos, sendo frequentemente utilizada para manipulação assíncrona de eventos de usuário.",
    "A Terra leva aproximadamente 365,25 dias para completar uma órbita ao redor do Sol.",
    "O ponto mais profundo dos oceanos, a Fossa das Marianas, tem cerca de 11.034 metros de profundidade.",
    "A atmosfera da Terra é composta principalmente por nitrogênio (78%) e oxigênio (21%).",
    "O Monte Everest, a montanha mais alta do mundo, tem uma altitude de 8.848 metros acima do nível do mar.",
    "A Grande Barreira de Coral, na Austrália, é a maior estrutura feita por organismos vivos e pode ser vista do espaço.",
    "A velocidade de rotação da Terra está diminuindo gradualmente devido à transferência de energia para a Lua.",
    "O deserto do Saara, na África, é o deserto mais quente do mundo, com temperaturas que podem atingir até 56,7 graus Celsius.",
    "O planeta Terra é o único corpo celeste conhecido a abrigar vida.",
    "O peso da atmosfera terrestre ao nível do mar é cerca de 101.325 pascals.",
    "O fenômeno da aurora boreal ocorre devido à interação entre partículas carregadas do Sol e os gases da atmosfera terrestre.",
    "A camada de ozônio na estratosfera protege a vida na Terra, absorvendo a maior parte da radiação ultravioleta do Sol.",
    "A água cobre aproximadamente 71% da superfície da Terra.",
    "O som se propaga mais rápido na água do que no ar, atingindo cerca de 1.480 metros por segundo.",
    "A Terra tem uma magnetosfera que protege a atmosfera superior do vento solar.",
    "O Polo Norte magnético não é fixo e se move gradualmente ao longo do tempo.",
    "O deslocamento continental é um processo contínuo, com as placas tectônicas se movendo a uma taxa de alguns centímetros por ano.",
    "O ponto mais próximo do espaço é o Monte Chimborazo, no Equador, devido à protuberância equatorial.",
    "A Antártica é o deserto mais frio e seco do planeta.",
    "A maior parte da água doce disponível na Terra está armazenada em geleiras e calotas polares.",
    "A cordilheira dos Andes é a mais longa cadeia de montanhas do mundo.",
    "O Oceano Pacífico é o maior e mais profundo dos oceanos.",
    "O maior lago de água doce em volume é o Lago Baikal, na Sibéria.",
    "O Monte Kilimanjaro, na Tanzânia, é o ponto mais alto da África, não considerando as ilhas.",
    "O Anel de Fogo do Pacífico é uma área de intensa atividade sísmica e vulcânica ao redor do Oceano Pacífico.",
    "A rocha mais antiga encontrada na Terra tem cerca de 4 bilhões de anos.",
    "A gravidade na superfície da Terra é mais fraca nos polos do que no equador devido à rotação.",
    "A Estação Espacial Internacional (ISS) orbita a Terra a uma velocidade de cerca de 28.000 quilômetros por hora.",
    "A Terra não é uma esfera perfeita devido à sua rotação, sendo ligeiramente achatada nos polos e alargada no equador.",
    "O rio Amazonas, na América do Sul, é o rio mais longo e tem o maior volume de água do mundo.",
    "O existencialismo é um movimento filosófico que se concentra na existência individual, liberdade e responsabilidade pessoal.",
    "Jean-Paul Sartre é considerado um dos principais expoentes do existencialismo, e sua obra 'O Ser e a Nada' é fundamental para a compreensão desse pensamento.",
    "A frase 'A existência precede a essência', atribuída a Sartre, resume a ideia de que a identidade de uma pessoa é construída ao longo da vida, em vez de ser predefinida.",
    "O existencialismo rejeita a ideia de uma natureza humana inata e defende a autonomia e liberdade individuais.",
    "Sartre argumenta que estamos 'condenados à liberdade', o que significa que somos responsáveis por nossas escolhas, mesmo quando tentamos evitar essa responsabilidade.",
    "Albert Camus, outro importante existencialista, abordou a questão do absurdo da vida, sugerindo que devemos confrontar o absurdo e viver com integridade.",
    "O termo 'angústia' é central na obra de Søren Kierkegaard, precursor do existencialismo, descrevendo a ansiedade existencial diante da liberdade de escolha.",
    "O existencialismo enfatiza a importância da experiência individual e subjetividade, colocando o indivíduo no centro da reflexão filosófica.",
    "A relação entre o eu e o outro é explorada por Simone de Beauvoir, que destaca a necessidade de superar relações opressoras e alcançar uma autenticidade pessoal.",
    "O existencialismo frequentemente confronta a questão da morte, levando à reflexão sobre como vivemos nossas vidas diante da finitude.",
    "Kierkegaard introduziu o conceito de 'estádios de existência', descrevendo diferentes modos de viver em termos de compromissos éticos e religiosos.",
    "Sartre popularizou a ideia de 'má-fé', que ocorre quando um indivíduo evita a responsabilidade, fingindo ser apenas um objeto no mundo.",
    "A filosofia existencialista influenciou a literatura, o cinema e a psicologia, destacando-se em obras como 'O Estrangeiro' de Camus e 'A Náusea' de Sartre.",
    "A noção de 'desespero' em Kierkegaard não se refere apenas à tristeza, mas sim à falta de compromisso com a busca de uma existência significativa.",
    "Sartre afirmou que 'a existência precede a essência' para enfatizar que os seres humanos não têm uma natureza predefinida ou um propósito inato.",
    "A ideia de 'autenticidade' na filosofia existencialista destaca a importância de viver de acordo com os próprios valores e não simplesmente seguir padrões sociais.",
    "O existencialismo frequentemente explora o conflito entre a liberdade individual e as estruturas sociais que podem limitar essa liberdade.",
    "O teatro do absurdo, representado por peças como 'Esperando Godot' de Samuel Beckett, é fortemente influenciado pelos temas existencialistas.",
    "A relação entre a existência e a temporalidade é uma preocupação central na filosofia existencialista, considerando como o tempo afeta a experiência humana.",
    "Beauvoir introduziu o conceito de 'Outro' para destacar a importância das relações sociais na formação da identidade individual.",
    "A filosofia existencialista tem raízes nas obras de Kierkegaard e Friedrich Nietzsche, que exploraram a condição humana e a crise de significado.",
    "Sartre é conhecido por sua declaração 'Estamos condenados a ser livres', refletindo a ideia de que a liberdade é uma carga constante para os indivíduos.",
    "O existencialismo enfatiza a responsabilidade individual, argumentando que cada pessoa é responsável por suas escolhas e ações.",
    "A busca pela autenticidade muitas vezes envolve confrontar a ansiedade e a incerteza inerentes à condição humana.",
    "A filosofia existencialista influenciou movimentos sociais, como o feminismo, ao questionar as normas tradicionais de gênero e destacar a importância da liberdade individual.",
    "A ideia de 'absurdo' na filosofia existencialista não implica necessariamente falta de sentido, mas sim a falta de sentido pré-determinado na vida.",
    "O existencialismo foi uma reação à filosofia tradicional, buscando uma abordagem mais pessoal e subjetiva para compreender a existência.",
    "A preocupação com a autenticidade na filosofia existencialista incentiva os indivíduos a se confrontarem com suas próprias verdadeiras intenções e valores.",
    "O existencialismo aborda questões universais, como a liberdade, o significado da vida e a busca por identidade, através de uma lente individualizada.",
    "A tomada de decisões é um processo complexo que envolve o cérebro em várias regiões, incluindo o córtex pré-frontal, o córtex cingulado anterior e o estriado.",
    "A neurociência identificou a amígdala como uma região crucial na avaliação de riscos e recompensas durante a tomada de decisões emocionais.",
    "O neurotransmissor dopamina desempenha um papel essencial na motivação e recompensa, influenciando as escolhas e a tomada de decisões.",
    "Estudos mostram que a falta de sono pode impactar negativamente a tomada de decisões, prejudicando a função do córtex pré-frontal.",
    "O fenômeno conhecido como 'paralisia da análise' ocorre quando a sobrecarga de informações prejudica a capacidade de tomar decisões eficazes.",
    "O viés de confirmação, onde tendemos a buscar informações que confirmam nossas crenças existentes, influencia significativamente o processo de tomada de decisões.",
    "A teoria da utilidade esperada, desenvolvida na economia comportamental, sugere que as pessoas tomam decisões com base na maximização da utilidade esperada.",
    "A plasticidade cerebral permite que o cérebro se adapte a novas informações e experiências, influenciando a forma como tomamos decisões ao longo do tempo.",
    "A tomada de decisões é afetada por fatores emocionais, como o medo e a ansiedade, que podem levar a escolhas mais conservadoras ou arriscadas.",
    "A empatia, relacionada à atividade do córtex pré-frontal, desempenha um papel na tomada de decisões sociais, considerando as emoções e perspectivas dos outros.",
    "A neuroeconomia combina princípios da neurociência e economia para entender melhor como o cérebro influencia as escolhas econômicas.",
    "O efeito de ancoragem é uma tendência de depender muito da primeira informação recebida ao tomar decisões, mesmo que seja irrelevante.",
    "A teoria da dissonância cognitiva, proposta por Leon Festinger, explora o desconforto psicológico que surge quando nossas crenças entram em conflito com nossas ações.",
    "O córtex orbitofrontal desempenha um papel crucial na avaliação de recompensas e punições, influenciando as decisões com base em experiências passadas.",
    "A dopamina também está envolvida na aversão à perda, influenciando a forma como avaliamos e reagimos a situações de risco.",
    "A neurociência destaca a importância da intuição na tomada de decisões, sugerindo que o cérebro processa informações subconscientes para orientar escolhas.",
    "A idade pode afetar a tomada de decisões, com pesquisas mostrando que adolescentes e idosos podem processar informações de maneira diferente de adultos jovens.",
    "A síndrome do paradoxo da escolha argumenta que ter muitas opções pode levar à insatisfação e dificultar a tomada de decisões.",
    "A ativação do córtex cingulado anterior está associada à detecção de conflitos durante a tomada de decisões, quando há escolhas difíceis de fazer.",
    "A teoria da dualidade de processamento propõe que a tomada de decisões envolva tanto processos automáticos e intuitivos quanto processos deliberativos e racionais.",
    "A memória de trabalho, que envolve a manutenção temporária de informações, desempenha um papel crucial na tomada de decisões diárias.",
    "A tomada de decisões éticas envolve áreas específicas do cérebro, como o córtex pré-frontal medial, que avalia as consequências morais das escolhas.",
    "A aversão à ambiguidade, uma preferência por informações claras, influencia as decisões ao lidar com situações incertas.",
    "A teoria da heurística da disponibilidade sugere que tendemos a dar mais peso a informações prontamente disponíveis ao tomar decisões.",
    "A ativação do núcleo accumbens, uma região associada à recompensa, está relacionada à busca por gratificação imediata durante a tomada de decisões.",
    "A tomada de decisões pode ser influenciada por processos inconscientes, como preconceitos e estereótipos, que afetam a avaliação de opções.",
    "A neurociência destaca a importância da regulação emocional na tomada de decisões, evitando que as emoções dominem o processo.",
    "A análise custo-benefício, uma abordagem econômica, também é aplicada na neurociência para entender como o cérebro avalia as escolhas.",
    "A capacidade de adiar a gratificação, controlando impulsos imediatos em favor de recompensas futuras, está relacionada à atividade do córtex pré-frontal.",
    "A arquitetura sustentável busca minimizar o impacto ambiental, promovendo o uso eficiente de recursos naturais e a redução de resíduos.",
    "Edifícios com certificação LEED (Liderança em Energia e Design Ambiental) seguem padrões rigorosos de sustentabilidade em design, construção e operação.",
    "Telhados verdes, cobertos com plantas, não apenas fornecem isolamento térmico, mas também absorvem água da chuva, reduzindo o escoamento pluvial.",
    "O uso de materiais reciclados, como a madeira recuperada, é uma prática comum na arquitetura sustentável para reduzir a demanda por recursos naturais.",
    "A iluminação natural é maximizada através do design de edifícios sustentáveis, reduzindo a necessidade de iluminação artificial durante o dia.",
    "Sistemas de captação de água da chuva são implementados para reutilizar a água em atividades como irrigação e descarga de vasos sanitários.",
    "Arquitetos sustentáveis consideram a orientação solar ao projetar edifícios, otimizando a entrada de luz natural e reduzindo a dependência de energia elétrica.",
    "Os edifícios passivos são projetados para maximizar o ganho solar e minimizar a perda de calor, reduzindo a necessidade de aquecimento ou resfriamento mecânico.",
    "A ventilação natural é incorporada ao design para melhorar a qualidade do ar interno e reduzir a dependência de sistemas de ventilação mecânica.",
    'O conceito de "Cradle to Cradle" visa criar edifícios que são totalmente recicláveis, sem gerar resíduos prejudiciais ao meio ambiente.',
    "A biomimética, inspirada na natureza, é usada na arquitetura sustentável para criar soluções eficientes e inovadoras em termos de energia e design.",
    "Os edifícios autossuficientes em energia usam fontes renováveis, como painéis solares e turbinas eólicas, para gerar toda a energia necessária.",
    "Materiais de baixo impacto ambiental, como bambu e cortiça, são utilizados na construção de edifícios sustentáveis.",
    "Jardins verticais não apenas melhoram a estética urbana, mas também proporcionam isolamento térmico e absorvem poluentes do ar.",
    "Arquitetura flutuante é uma solução inovadora para enfrentar inundações, criando estruturas que se elevam com o aumento do nível da água.",
    "Os edifícios sustentáveis priorizam a eficiência energética, utilizando isolamento térmico e janelas de alto desempenho para reduzir a perda de calor.",
    "O design passivo solar aproveita a energia do sol para aquecer espaços internos, reduzindo a necessidade de sistemas de aquecimento.",
    "Sistemas de automação residencial são utilizados para otimizar o uso de energia, ajustando iluminação, temperatura e outros parâmetros automaticamente.",
    "A arquitetura sustentável busca integrar espaços verdes, como parques e jardins, nas áreas urbanas para promover a biodiversidade e o bem-estar.",
    "O upcycling é uma prática comum na arquitetura sustentável, transformando materiais descartados em novos produtos de maior valor.",
    "A reabilitação de edifícios antigos para padrões sustentáveis é uma abordagem para preservar o patrimônio arquitetônico e reduzir o desperdício de recursos.",
    "Telhados solares não apenas geram energia, mas também proporcionam sombra, melhorando o conforto térmico e reduzindo a carga nos sistemas de resfriamento.",
    "Os edifícios sustentáveis frequentemente incorporam sistemas de irrigação eficientes para minimizar o uso de água em paisagismo.",
    "A arquitetura sustentável visa criar ambientes internos saudáveis, utilizando materiais de baixa emissão e sistemas de ventilação eficazes.",
    "A construção modular é uma abordagem sustentável, pois reduz o desperdício de materiais e permite a reutilização de componentes em diferentes projetos.",
    "O design de edifícios sustentáveis considera o ciclo de vida completo, desde a extração de materiais até a demolição e reciclagem.",
    "As cidades sustentáveis incorporam planejamento urbano que promove transporte público eficiente, espaços verdes acessíveis e edifícios energeticamente eficientes.",
    "A arquitetura sustentável busca equilibrar as necessidades humanas com a preservação do meio ambiente, promovendo uma coexistência harmoniosa.",
    "O uso de painéis solares transparentes em fachadas de edifícios permite a geração de energia sem comprometer a entrada de luz natural.",
    "A economia comportamental combina princípios da psicologia com teorias econômicas para entender como as pessoas tomam decisões financeiras.",
    "Daniel Kahneman e Amos Tversky são considerados os fundadores da economia comportamental, destacando vieses cognitivos e heurísticas na tomada de decisões.",
    "O fenômeno conhecido como 'aversão à perda' destaca que as pessoas valorizam mais evitar perdas do que obter ganhos equivalentes.",
    "A teoria da perspectiva sugere que as pessoas avaliam as opções com base em ganhos e perdas percebidos em relação a um ponto de referência.",
    "O efeito manada, onde as pessoas seguem as decisões do grupo em vez de realizar uma análise independente, é um comportamento comum na economia comportamental.",
    "A ancoragem é um viés cognitivo em que as pessoas baseiam suas decisões em valores iniciais, mesmo que sejam irrelevantes para a situação.",
    "A teoria do impulso sugere que as decisões financeiras são frequentemente influenciadas por emoções momentâneas e estados de espírito.",
    "O overconfidence, ou excesso de confiança, é um viés comportamental em que as pessoas tendem a superestimar suas habilidades e conhecimentos.",
    "O paradoxo da escolha destaca que ter muitas opções pode levar à indecisão e insatisfação, contrariando a ideia de que mais escolhas são sempre melhores.",
    "A procrastinação é um comportamento comum na economia comportamental, influenciando atrasos em decisões financeiras importantes.",
    "O fenômeno da aversão à ambiguidade destaca a tendência das pessoas em preferir situações onde têm mais informações claras em detrimento de situações incertas.",
    "O viés de confirmação, onde as pessoas buscam informações que confirmam suas crenças existentes, influencia a análise seletiva de dados na tomada de decisões.",
    "O modelo de intertemporalidade explora como as pessoas valorizam recompensas e custos ao longo do tempo, impactando escolhas como economizar ou gastar.",
    "O campo da neuroeconomia combina a economia comportamental com a neurociência para estudar como o cérebro influencia o comportamento econômico.",
    "A teoria da aversão à perda assimétrica argumenta que as pessoas são mais sensíveis a perdas do que a ganhos equivalentes.",
    "O desconto hiperbólico é um fenômeno em que as pessoas dão mais peso a recompensas imediatas em comparação com recompensas futuras, mesmo que sejam maiores.",
    "O conceito de 'dinheiro mental' destaca como as pessoas categorizam e atribuem significados emocionais a diferentes fontes de dinheiro em suas vidas.",
    "A teoria dos custos afundados sugere que as pessoas têm dificuldade em abandonar um investimento mesmo quando ele não é mais viável, devido ao investimento emocional anterior.",
    "O modelo de agente principal explora como as relações de agência influenciam as decisões financeiras entre partes com interesses diferentes.",
    "O uso do nudging, ou empurrão suave, é uma estratégia na economia comportamental que utiliza sugestões indiretas para influenciar escolhas sem impor restrições.",
    "A economia comportamental enfatiza a importância de considerar a irracionalidade humana na modelagem de comportamento econômico.",
    "O viés de representatividade leva as pessoas a fazerem julgamentos com base em estereótipos e generalizações, influenciando a avaliação de riscos e recompensas.",
    "A teoria da troca social explora como as normas sociais e as relações interpessoais afetam as decisões financeiras e as preferências individuais.",
    "A teoria da autocontrole aborda a capacidade limitada das pessoas de resistir a tentações de curto prazo em favor de benefícios de longo prazo.",
    "O viés de endowment, ou efeito de posse, destaca que as pessoas tendem a atribuir um valor mais alto aos itens simplesmente por possuí-los.",
    "A economia comportamental destaca a importância de considerar o contexto e a situação na compreensão das decisões financeiras das pessoas.",
    "A teoria dos jogos, aplicada na economia comportamental, explora como as interações estratégicas entre os indivíduos afetam as decisões e os resultados.",
    "O campo da economia experimental, que utiliza experimentos controlados para estudar comportamentos econômicos, é uma ferramenta comum na economia comportamental.",
    "O viés de otimismo é a tendência das pessoas em subestimar os riscos associados a suas próprias decisões, acreditando que têm menos probabilidade de enfrentar eventos negativos.",
    "A inteligência artificial ética busca desenvolver sistemas de IA que operem de maneira justa, transparente e responsável.",
    "Os princípios da IA ética incluem transparência, responsabilidade, imparcialidade, privacidade e a busca pelo bem comum.",
    "A preocupação com a justiça social é uma parte essencial da inteligência artificial ética, buscando evitar discriminações e desigualdades.",
    "A coleta ética de dados é crucial para garantir que os conjuntos de dados usados ​​na IA não perpetuem vieses existentes na sociedade.",
    "A interpretabilidade dos modelos de IA é um desafio na ética da inteligência artificial, pois é importante compreender como as decisões são tomadas.",
    "A IA ética reconhece a importância de envolver diversas vozes e perspectivas na concepção, desenvolvimento e implementação de sistemas de IA.",
    "Os testes de viés são ferramentas utilizadas na IA ética para avaliar e mitigar a presença de preconceitos em modelos de aprendizado de máquina.",
    "A ética da IA aborda preocupações sobre o impacto potencial da automação no emprego e na economia global.",
    "A responsabilidade algorítmica destaca a necessidade de garantir que os desenvolvedores de IA sejam responsáveis pelos resultados de seus sistemas.",
    "A IA ética também se preocupa com o impacto psicológico e emocional do uso de sistemas de IA em indivíduos e sociedades.",
    "A privacidade é uma questão fundamental na inteligência artificial ética, com foco na proteção dos dados pessoais dos usuários.",
    "A transparência algorítmica refere-se à necessidade de divulgar informações sobre como os algoritmos de IA tomam decisões.",
    "A ética da IA considera o impacto ambiental, buscando desenvolver modelos e algoritmos mais eficientes em termos de energia.",
    "A necessidade de sistemas de IA serem robustos diante de adversidades e ataques é uma preocupação ética importante.",
    "A ética da IA se estende ao desenvolvimento de armas autônomas, levantando questões sobre a tomada de decisões por máquinas em contextos de conflito.",
    "A ética do reconhecimento facial envolve preocupações sobre vigilância em massa, discriminação e ameaças à privacidade.",
    "A inteligência artificial ética busca promover a inclusão digital, garantindo que os benefícios da tecnologia se estendam a todas as comunidades.",
    "A participação pública na tomada de decisões sobre o desenvolvimento de sistemas de IA é promovida pela ética da IA para garantir uma abordagem democrática.",
    "A preocupação com a singularidade ética refere-se ao momento hipotético em que a IA atinge um nível de inteligência que ultrapassa a capacidade humana de compreensão.",
    "A ética da IA abrange a responsabilidade das empresas no desenvolvimento e uso de tecnologias de IA.",
    "A ética da IA considera o ciclo de vida completo dos sistemas, desde a concepção até a retirada e descarte responsável.",
    "A ética da IA também aborda questões de propriedade intelectual e direitos autorais relacionados a algoritmos e modelos desenvolvidos por IA.",
    "A explanação ética refere-se à necessidade de explicar como os sistemas de IA funcionam de maneira compreensível para os usuários e partes interessadas.",
    "A ética da IA aborda a questão da accountability, assegurando que haja mecanismos para responsabilizar as partes envolvidas em casos de mau uso ou resultados prejudiciais.",
    "A ética da IA reconhece a importância da educação e conscientização sobre as implicações éticas da tecnologia em todos os níveis da sociedade.",
    "A colaboração internacional é promovida pela ética da IA para desenvolver padrões globais e diretrizes éticas para o uso responsável da tecnologia.",
    "A ética da IA incentiva a pesquisa contínua para aprimorar métodos de avaliação ética, auditoria de sistemas de IA e desenvolvimento de soluções éticas.",
    "A ética da IA aborda o dilema ético de conceder ou não a sistemas de IA autonomia para tomar decisões críticas sem intervenção humana.",
    "A resiliência ética refere-se à capacidade dos sistemas de IA de se adaptarem eticamente a mudanças nas circunstâncias e requisitos sociais.",
    "A psicologia positiva é uma abordagem que se concentra no estudo e promoção dos aspectos positivos da experiência humana.",
    "Martin Seligman, conhecido como o fundador da psicologia positiva, buscou mudar o foco tradicional da psicologia centrada nos problemas para uma perspectiva mais otimista.",
    "A gratidão, prática comum na psicologia positiva, envolve reconhecer e apreciar as coisas positivas na vida, promovendo bem-estar emocional.",
    "A resiliência é um tema central na psicologia positiva, abordando a capacidade de enfrentar desafios e superar adversidades.",
    "A autenticidade, ser verdadeiro consigo mesmo e com os outros, é valorizada na psicologia positiva como um componente chave da satisfação pessoal.",
    "A psicologia positiva destaca a importância de cultivar e fortalecer relacionamentos saudáveis para promover o bem-estar emocional.",
    "A teoria do florescimento, dentro da psicologia positiva, refere-se à busca ativa da realização pessoal e do potencial humano.",
    "O otimismo, considerando os eventos de uma maneira positiva, é um componente essencial na psicologia positiva para promover a resiliência.",
    "A savorização, ou apreciação consciente, é uma prática da psicologia positiva que envolve desfrutar plenamente de experiências positivas.",
    "A psicologia positiva busca não apenas tratar distúrbios mentais, mas também promover o florescimento humano e a busca da felicidade.",
    "O conceito de 'flow', proposto por Mihaly Csikszentmihalyi, destaca a experiência de profundo envolvimento e satisfação em atividades desafiadoras.",
    "A psicologia positiva encoraja a descoberta e o cultivo dos pontos fortes individuais, promovendo o autodesenvolvimento.",
    "A prática da atenção plena, também conhecida como mindfulness, é comumente incorporada na psicologia positiva para promover a consciência do momento presente.",
    "A psicologia positiva reconhece a importância de metas e aspirações significativas na promoção do sentido de vida e realização pessoal.",
    "A empatia é valorizada na psicologia positiva como uma habilidade que fortalece os relacionamentos e promove a compreensão mútua.",
    "A busca por significado, compreendendo o propósito e o significado da vida, é um tema explorado na psicologia positiva.",
    "A psicologia positiva destaca a importância do perdão na promoção da saúde mental, permitindo a superação de ressentimentos e mágoas.",
    "O humor e a capacidade de rir são vistos como aspectos essenciais da psicologia positiva para aliviar o estresse e promover o bem-estar emocional.",
    "A resolução de conflitos de maneira construtiva é uma habilidade promovida pela psicologia positiva para fortalecer relacionamentos.",
    "A criação de hábitos saudáveis, como exercícios regulares e uma dieta equilibrada, é encorajada na psicologia positiva para promover a saúde física e mental.",
    "A psicologia positiva reconhece a importância da comunidade e da conexão social na promoção do bem-estar emocional.",
    "A aceitação, compreendendo e abraçando a realidade, é uma prática promovida pela psicologia positiva para lidar com desafios.",
    "A psicologia positiva incentiva a prática da generosidade e atos de bondade como meios de promover o bem-estar próprio e dos outros.",
    "A apreciação da beleza e da excelência, conhecida como apreciação estética, é um elemento importante na psicologia positiva.",
    "A autorregulação emocional, a capacidade de gerenciar e controlar emoções, é uma competência promovida pela psicologia positiva.",
    "A psicologia positiva destaca a importância da educação emocional, capacitando as pessoas a compreender e expressar suas emoções de maneira saudável.",
    "A psicologia positiva reconhece que a felicidade é um estado complexo e multidimensional, indo além da simples ausência de sofrimento.",
    "A prática da visualização positiva, imaginando um futuro positivo, é comumente incorporada na psicologia positiva para promover metas e aspirações.",
    "A psicologia positiva destaca a importância da autocompaixão, cultivando uma atitude gentil e compassiva em relação a si mesmo.",
    "As energias renováveis são fontes de energia que são naturalmente reabastecidas, como solar, eólica, hidrelétrica e biomassa.",
    "A energia solar é gerada pela captura da luz do sol e sua conversão em eletricidade ou calor, sendo uma fonte abundante e limpa.",
    "Os painéis solares fotovoltaicos convertem a luz solar diretamente em eletricidade através do efeito fotovoltaico, uma descoberta crucial na energia solar.",
    "A energia eólica é gerada pelo movimento das turbinas eólicas, convertendo a energia cinética do vento em eletricidade.",
    "A maior fazenda eólica do mundo, em Gansu, China, tem capacidade para produzir mais de 6 gigawatts de eletricidade.",
    "A energia hidrelétrica aproveita o movimento da água para gerar eletricidade, sendo uma das fontes mais antigas e amplamente utilizadas de energia renovável.",
    "A usina hidrelétrica de Itaipu, na fronteira entre Brasil e Paraguai, é uma das maiores do mundo em capacidade de geração de energia.",
    "A energia geotérmica utiliza o calor da Terra para gerar eletricidade, sendo aplicada em regiões com atividade geotérmica significativa, como Islândia e Nova Zelândia.",
    "A Islândia obtém grande parte de sua eletricidade a partir de fontes geotérmicas, aproveitando seu rico potencial geotérmico.",
    "A biomassa é uma fonte de energia renovável que utiliza matéria orgânica, como resíduos agrícolas e de madeira, para gerar eletricidade ou calor.",
    "O biogás, produzido a partir da decomposição de resíduos orgânicos, é utilizado como fonte de energia renovável para produção de eletricidade e aquecimento.",
    "O Brasil é um líder global em biocombustíveis, especialmente etanol derivado da cana-de-açúcar, uma importante fonte de energia renovável para veículos.",
    "A energia das ondas e das marés é gerada pela captura do movimento das ondas e das correntes oceânicas para produzir eletricidade.",
    "A Escócia é lar de várias instalações de energia das marés, incluindo a barragem de marés de MeyGen, uma das maiores do mundo.",
    "A energia das correntes oceânicas tem um grande potencial como fonte de energia renovável, aproveitando as correntes submarinas para gerar eletricidade.",
    "Os biocombustíveis avançados, produzidos a partir de matérias-primas não alimentares, representam uma alternativa sustentável aos combustíveis fósseis.",
    "A energia solar flutuante, com painéis solares instalados em corpos d'água, está sendo cada vez mais adotada como uma forma eficiente de geração de energia.",
    "A Noruega é líder em energia hidrelétrica na Europa, com a maioria de sua eletricidade proveniente de usinas hidrelétricas.",
    "A energia maremotriz, gerada pelo movimento vertical das marés, é uma forma previsível e constante de energia renovável.",
    "A Índia lançou o maior parque solar do mundo, o Pavagada Solar Park, com uma capacidade planejada de mais de 2 gigawatts.",
    "A energia renovável está se tornando cada vez mais competitiva em termos de custos, tornando-se uma escolha econômica e sustentável.",
    "A integração de armazenamento de energia, como baterias avançadas, é crucial para superar a intermitência de fontes como solar e eólica.",
    "O movimento global em direção à eletrificação, especialmente em veículos, impulsiona a demanda por energia renovável para reduzir as emissões de carbono.",
    "A adoção de microrredes, sistemas de energia independentes, está crescendo como uma solução descentralizada e resiliente, impulsionada por energias renováveis.",
    "A União Europeia tem metas ambiciosas para alcançar a neutralidade de carbono até 2050, impulsionando investimentos em energias renováveis.",
    "A energia renovável desempenha um papel crucial na mitigação das mudanças climáticas, reduzindo as emissões de gases de efeito estufa associadas aos combustíveis fósseis.",
    "A mini e microgeração de energia renovável, como painéis solares em residências, permite aos consumidores gerar sua própria eletricidade e reduzir a dependência da rede.",
    "O setor de energias renováveis cria empregos significativos em áreas como instalação, manutenção e fabricação de tecnologias sustentáveis.",
    "A transição para uma matriz energética baseada em renováveis é essencial para alcançar os objetivos de sustentabilidade e enfrentar os desafios da mudança climática."
  ];

  const [curiosidadeAtual, setCuriosidadeAtual] = useState(
    Math.floor(Math.random() * curiosidades.length)
  );

  useEffect(() => {
    const interval = setInterval(() => {
      setCuriosidadeAtual(Math.floor(Math.random() * curiosidades.length));
    }, 6000);

    return () => clearInterval(interval);
  }, [curiosidadeAtual, curiosidades.length]);

  return <Typography className={style.curiosityText}>{curiosidades[curiosidadeAtual]}</Typography>;
};
